version: '3'

services:

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    image: webapi/api

  developer:
    build:
      context: ./src/developer
      dockerfile: Dockerfile
    image: webapi/developer

  db:
    build:
      context: .
      dockerfile: data/pg/Dockerfile
    image: webapi/db

  explorer:
    build:
      context: ./src/explorer
      dockerfile: Dockerfile
    image: webapi/explorer

  address-parser:
    build:
      context: ./src/address-parser
      dockerfile: Dockerfile
    image: webapi/address-parser

  cache:
    image: redis:latest
