# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import address_parser_pb2 as address__parser__pb2


class AddressServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/addressparser.AddressService/Parse',
                request_serializer=address__parser__pb2.InputAddress.SerializeToString,
                response_deserializer=address__parser__pb2.Address.FromString,
                )


class AddressServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Parse(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=address__parser__pb2.InputAddress.FromString,
                    response_serializer=address__parser__pb2.Address.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addressparser.AddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddressService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/addressparser.AddressService/Parse',
            address__parser__pb2.InputAddress.SerializeToString,
            address__parser__pb2.Address.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
