# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_parser.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='address_parser.proto',
  package='addressparser',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.routeguideB\023AddressServiceProtoP\001\242\002\004AGRC',
  serialized_pb=b'\n\x14\x61\x64\x64ress_parser.proto\x12\raddressparser\"\x86\x02\n\x07\x41\x64\x64ress\x12\x16\n\x0e\x61\x64\x64ress_number\x18\x01 \x01(\t\x12\x1d\n\x15\x61\x64\x64ress_number_suffix\x18\x02 \x01(\t\x12\x18\n\x10prefix_direction\x18\x03 \x01(\t\x12\x13\n\x0bstreet_name\x18\x04 \x01(\t\x12\x18\n\x10street_direction\x18\x05 \x01(\t\x12\x13\n\x0bstreet_type\x18\x06 \x01(\t\x12\x11\n\tunit_type\x18\x07 \x01(\t\x12\x0f\n\x07unit_id\x18\x08 \x01(\t\x12\x0c\n\x04\x63ity\x18\t \x01(\t\x12\x10\n\x08zip_code\x18\n \x01(\t\x12\x0e\n\x06po_box\x18\x0b \x01(\t\x12\x12\n\nnormalized\x18\x0c \x01(\t\"\x1f\n\x0cInputAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2P\n\x0e\x41\x64\x64ressService\x12>\n\x05Parse\x12\x1b.addressparser.InputAddress\x1a\x16.addressparser.Address\"\x00\x42;\n\x1bio.grpc.examples.routeguideB\x13\x41\x64\x64ressServiceProtoP\x01\xa2\x02\x04\x41GRCb\x06proto3'
)




_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='addressparser.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_number', full_name='addressparser.Address.address_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_number_suffix', full_name='addressparser.Address.address_number_suffix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix_direction', full_name='addressparser.Address.prefix_direction', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street_name', full_name='addressparser.Address.street_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street_direction', full_name='addressparser.Address.street_direction', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street_type', full_name='addressparser.Address.street_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_type', full_name='addressparser.Address.unit_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_id', full_name='addressparser.Address.unit_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='addressparser.Address.city', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zip_code', full_name='addressparser.Address.zip_code', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='po_box', full_name='addressparser.Address.po_box', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized', full_name='addressparser.Address.normalized', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=302,
)


_INPUTADDRESS = _descriptor.Descriptor(
  name='InputAddress',
  full_name='addressparser.InputAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='addressparser.InputAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=335,
)

DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['InputAddress'] = _INPUTADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'address_parser_pb2'
  # @@protoc_insertion_point(class_scope:addressparser.Address)
  })
_sym_db.RegisterMessage(Address)

InputAddress = _reflection.GeneratedProtocolMessageType('InputAddress', (_message.Message,), {
  'DESCRIPTOR' : _INPUTADDRESS,
  '__module__' : 'address_parser_pb2'
  # @@protoc_insertion_point(class_scope:addressparser.InputAddress)
  })
_sym_db.RegisterMessage(InputAddress)


DESCRIPTOR._options = None

_ADDRESSSERVICE = _descriptor.ServiceDescriptor(
  name='AddressService',
  full_name='addressparser.AddressService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=337,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='addressparser.AddressService.Parse',
    index=0,
    containing_service=None,
    input_type=_INPUTADDRESS,
    output_type=_ADDRESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDRESSSERVICE)

DESCRIPTOR.services_by_name['AddressService'] = _ADDRESSSERVICE

# @@protoc_insertion_point(module_scope)
